database:
  host: database
  port: 5432
  user: postgres
  password: mysecretpassword
  database: postgres
  insecure: true
oauth:
  clientId: <client_id> # fill this in with your client id
  clientSecret: <client_secret> # fill this in with your client secret
  redirectUri: http://127.0.0.1:8080/auth/callback
authStore:
  name: authStore
  secret: mysecretpassword
jwt:
  secret: mysecretpassword
